FROM --platform=linux/amd64 python:3.10-slim

RUN apt-get update && apt-get install -y \
    libsndfile1 \
    ffmpeg \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-birdnet.txt ./requirements.txt
COPY aggregator.py .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH="/app/models:${PYTHONPATH}"

COPY . .

CMD ["python", "run_model.py"]