FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    libsndfile1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-perch.txt ./requirements.txt

COPY run_model.py ./

COPY models/audio_utils.py models/perch_adapter.py ./models/

COPY models/perch_model ./models/perch_model

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "run_model.py"]