FROM --platform=linux/amd64 python:3.9-slim

RUN apt-get update && apt-get install -y \
    libsndfile1 \
    ffmpeg \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements-birdnet.txt ./requirements.txt

COPY run_model.py aggregator.py ./

COPY models/audio_utils.py models/birdnet_adapter.py models/__init__.py  ./models/


RUN pip install --no-cache-dir -r requirements.txt


CMD ["python", "run_model.py"]